### ISSUE TITLE
fan-in calculation in  _equalized_deconv2d

### ISSUE THREAD

**Issue by talkenig** [akanimax/pro_gan_pytorch#44]
Hi! First of all thanks for your implementation - the code is very nice! I am using it as a reference for some of the special blocks, and I noticed that in  _equalized_deconv2d ([here](https://github.com/akanimax/pro_gan_pytorch/blob/126a953548851f53e19893f5d5e82d87125f04b2/pro_gan_pytorch/CustomLayers.py#L88)) you define the fan_in variable as the number of input channels, so the kernel size is not taken into consideration. After seeing this, I compared to the official TF implementation, where they use the kernel size ([here](https://github.com/tkarras/progressive_growing_of_gans/blob/master/networks.py#L88)).
So wanted to ask if this is intentional, and if so, then why did you do that.
Thanks in advance.

**Comment by akanimax** [comment]
@talkenig, 

Thanks for the appreciation :+1:. Wow, I really had to scratch my head why I designed it like this :rofl:. The reason is that I implemented the `_equalized_deconv2d` layer to emulate a fully connected layer at the beginning of the generator. As in going from `[B x 512 x 1 x 1]` to `[B x 512 x 4 x 4]`. I didn't want to increase the unnecessary overhead of flattening the input and applying a fully connected layer (Which the official implementation does [here](https://github.com/tkarras/progressive_growing_of_gans/blob/master/networks.py#L184)). Besides,  in general for a `transposed_conv` layer, since the operation has a receptive field of `1x1`, the fan-in would always be simply equal to `channels_in`. 
Hope this helps :+1:. 
Please feel free to ask if you have any other questions :smile:.

Cheers :beers:!
@akanimax

**Comment by talkenig** [comment]
Thanks for your response. I understand your usage here, but I do not understand the comment that a transposed_conv layer has a receptive field of 1x1. If you specify a kernel size larger than 1, then the transposed convolution will have a receptive field of k x k. Please correct me if I got something wrong. 
I do understand that you are doing it to go from 1x1xc to 4x4xc, so I understand this specific case, but asking in general. Also, you could have used regular convolution here for this block, right? Shouldn't make a difference if the stride is 1.
